apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: demo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
